// <auto-generated/>

namespace MyTelegram.Schema;

[TlObject(0x73f1f8dc)]
public class TMsgContainer : IRequest<IObject>
{
    public uint ConstructorId => 0x73f1f8dc;
    public TContainerMessage[] Messages { get; set; }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Messages.Length);
        foreach (var containerMessage in Messages)
        {
            writer.Write(containerMessage);
        }
    }

    /// <summary>
    ///     Smallest possible on-wire msg_container entry: msg_id(8) + seqno(4) + bytes(4) + constructor id(4).
    /// </summary>
    private const int MinEntrySize = 20;

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        var length = buffer.ReadInt32();

        // The entry count is attacker-controlled. Allocating on it before checking that the remaining
        // buffer could even hold that many entries lets a few bytes request a multi-gigabyte array.
        if (length < 0 || (long)length * MinEntrySize > buffer.Length)
        {
            throw new InvalidOperationException(
                $"Invalid msg_container length: {length}, remaining buffer: {buffer.Length}.");
        }

        if (length > 0)
        {
            Messages = new TContainerMessage[length];
            for (int i = 0; i < length; i++)
            {
                var item = new TContainerMessage();
                item.Deserialize(ref buffer);
                Messages[i] = item;
            }
        }
    }
}