// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// Create and upload a new <a href="https://corefork.telegram.org/api/wallpapers">wallpaper</a>
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 WALLPAPER_FILE_INVALID The specified wallpaper file is invalid.</c></para>
/// <para><c>400 WALLPAPER_MIME_INVALID The specified wallpaper MIME type is invalid. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/account.uploadWallPaper" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0xdd853661)]
public sealed partial class RequestUploadWallPaper : IRequest<MyTelegram.Schema.IWallPaper>
{
    public uint ConstructorId => 0xdd853661;

    /// <summary>
    /// The JPG/PNG wallpaper
    /// See <a href="https://corefork.telegram.org/type/InputFile" />
    /// </summary>
    public MyTelegram.Schema.IInputFile File { get; set; }

    /// <summary>
    /// MIME type of uploaded wallpaper
    /// </summary>
    public string MimeType { get; set; }

    /// <summary>
    /// Wallpaper settings
    /// See <a href="https://corefork.telegram.org/type/WallPaperSettings" />
    /// </summary>
    public MyTelegram.Schema.IWallPaperSettings Settings { get; set; }

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(File);
        writer.Write(MimeType);
        writer.Write(Settings);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        File = buffer.Read<MyTelegram.Schema.IInputFile>();
        MimeType = buffer.ReadString();
        Settings = buffer.Read<MyTelegram.Schema.IWallPaperSettings>();
    }
}
