using MyTelegram.Messenger.Services.HistoryImport;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Messages;
/// <summary>
/// Obtains information about a chat export file, generated by a foreign chat app, <a href="https://corefork.telegram.org/api/import">click here for more info about imported chats »</a>.
/// Possible errors
/// Code Type Description
/// 400 IMPORT_FORMAT_UNRECOGNIZED The specified chat export file was exported from an unsupported chat app.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.checkHistoryImport"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class CheckHistoryImportHandler(IChatExportParser chatExportParser)
    : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestCheckHistoryImport,
        MyTelegram.Schema.Messages.IHistoryImportParsed>
{
    protected override Task<MyTelegram.Schema.Messages.IHistoryImportParsed> HandleCoreAsync(IRequestInput input,
        MyTelegram.Schema.Messages.RequestCheckHistoryImport obj)
    {
        if (string.IsNullOrWhiteSpace(obj.ImportHead))
        {
            RpcErrors.RpcErrors400.ImportFileInvalid.ThrowRpcError();
        }

        // The clients send the first 100 lines of the export file, which is all the server needs to
        // tell the app it came from and whether it is a private or a group chat.
        var head = chatExportParser.ParseHead(obj.ImportHead);
        if (head == null)
        {
            RpcErrors.RpcErrors400.ImportFormatUnrecognized.ThrowRpcError();
        }

        return Task.FromResult<MyTelegram.Schema.Messages.IHistoryImportParsed>(
            new MyTelegram.Schema.Messages.THistoryImportParsed
            {
                Pm = head!.IsPm,
                Group = head.IsGroup,
                Title = string.IsNullOrWhiteSpace(head.Title) ? null : head.Title
            });
    }
}