namespace MyTelegram.Messenger.Handlers.LatestLayer.Messages;
/// <summary>
/// Get info about chat invites generated by admins.
/// Possible errors
/// Code Type Description
/// 400 CHAT_ADMIN_REQUIRED You must be an admin in this chat to do this.
/// 403 CHAT_WRITE_FORBIDDEN You can't write in this chat.
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.getAdminsWithInvites"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class GetAdminsWithInvitesHandler(IQueryProcessor queryProcessor, IAccessHashHelper accessHashHelper, IUserConverterService userConverterService, IPeerHelper peerHelper, IChannelAppService channelAppService) : RpcResultObjectHandler<RequestGetAdminsWithInvites, IChatAdminsWithInvites>
{
    protected override async Task<IChatAdminsWithInvites> HandleCoreAsync(IRequestInput input, RequestGetAdminsWithInvites obj)
    {
        await accessHashHelper.CheckAccessHashAsync(input, obj.Peer);
        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        if (peer.PeerType != PeerType.Channel)
        {
            RpcErrors.RpcErrors400.PeerIdInvalid.ThrowRpcError();
        }

        var channelReadModel = await channelAppService.GetAsync(peer.PeerId);
        if (channelReadModel == null)
        {
            RpcErrors.RpcErrors400.PeerIdInvalid.ThrowRpcError();
        }

        if (!channelReadModel!.AdminList.Any(p => p.UserId == input.UserId))
        {
            RpcErrors.RpcErrors400.ChatAdminRequired.ThrowRpcError();
        }

        var adminWithInvitesList = await queryProcessor.ProcessAsync(new GetAdminInvitesQuery(peer.PeerId));
        var userIds = adminWithInvitesList.Select(p => p.AdminId).ToList();
        var users = await userConverterService.GetUserListAsync(input, userIds, false, false, input.Layer);
        return new TChatAdminsWithInvites
        {
            Admins = [..adminWithInvitesList.Select(p => new TChatAdminWithInvites { AdminId = p.AdminId, InvitesCount = p.InvitesCount, RevokedInvitesCount = p.RevokedInvitesCount })],
            Users = [..users]
        };
    }
}
