using MyTelegram.Messenger.Services.Dice;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Messages;
/// <summary>
/// Save a message <a href="https://corefork.telegram.org/api/drafts">draft</a> associated to a chat.
/// Possible errors
/// Code Type Description
/// 400 CHAT_ADMIN_REQUIRED You must be an admin in this chat to do this.
/// 400 ENTITY_BOUNDS_INVALID A specified <a href="https://corefork.telegram.org/api/entities#entity-length">entity offset or length</a> is invalid, see <a href="https://corefork.telegram.org/api/entities#entity-length">here »</a> for info on how to properly compute the entity offset/length.
/// 400 INPUT_USER_DEACTIVATED The specified user was deleted.
/// 400 MSG_ID_INVALID Invalid message ID provided.
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.saveDraft"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class SaveDraftHandler(ICommandBus commandBus, IPeerHelper peerHelper, IMediaHelper mediaHelper, IMessageEffectAppService messageEffectAppService, IMessageEntityService messageEntityService) : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestSaveDraft, IBool>
{
    protected override async Task<IBool> HandleCoreAsync(IRequestInput input, RequestSaveDraft obj)
    {
        MessageLengthHelper.ValidateMessage(obj.Message);

        // A draft is never autolinked: the server only generates the autogenerated entities when the
        // text is actually sent. See https://corefork.telegram.org/api/entities
        var entities = messageEntityService.ValidateAndNormalize(obj.Message, obj.Entities);

        int? replyToMsgId = null;
        switch (obj.ReplyTo)
        {
            case null:
                break;
            case TInputReplyToMessage inputReplyToMessage:
                replyToMsgId = inputReplyToMessage.ReplyToMsgId;
                break;
            case TInputReplyToMonoForum:
                break;
            case TInputReplyToStory:
                break;
            default:
                throw new ArgumentOutOfRangeException();
        }

        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var dialogId = DialogId.Create(input.UserId, peer);
        IMessageMedia? media = null;
        if (obj.Media != null)
        {
            // A dice has no local form to save: converting it here would roll a value that is then stored
            // in the draft and sent later as a stale outcome. TDLib's can_be_local_message_content is false.
            DiceMediaGuard.ThrowIfDice(obj.Media);

            media = await mediaHelper.SaveMediaAsync(obj.Media);
        }

        var effect = await messageEffectAppService.ValidateEffectAsync(obj.Effect, input.UserId, peer.PeerType);

        var saveDraftCommand = new SaveDraftCommand(dialogId, input.ToRequestInfo(), new Draft(obj.NoWebpage, obj.InvertMedia, replyToMsgId, obj.Message, CurrentDate, entities2: entities, media: media, effect: effect, media2: obj.Media, replyTo: obj.ReplyTo, suggestedPost: obj.SuggestedPost), null);
        await commandBus.PublishAsync(saveDraftCommand);
        return new TBoolTrue();
    }
}