using MyTelegram.Messenger.Services.Dice;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Messages;
/// <summary>
/// Save a message <a href="https://corefork.telegram.org/api/drafts">draft</a> associated to a chat.
/// Possible errors
/// Code Type Description
/// 400 CHAT_ADMIN_REQUIRED You must be an admin in this chat to do this.
/// 400 ENTITY_BOUNDS_INVALID A specified <a href="https://corefork.telegram.org/api/entities#entity-length">entity offset or length</a> is invalid, see <a href="https://corefork.telegram.org/api/entities#entity-length">here »</a> for info on how to properly compute the entity offset/length.
/// 400 INPUT_USER_DEACTIVATED The specified user was deleted.
/// 400 MSG_ID_INVALID Invalid message ID provided.
/// 400 PEER_ID_INVALID The provided peer id is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.saveDraft"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
///
/// <para><c>MSG_ID_INVALID</c> is deliberately not enforced for the reply target. A draft is not a
/// message: the reply is only resolved when it is actually sent, and answering with an error here
/// would make a draft whose target has since been deleted impossible to save at all — clients retry
/// the same request on every keystroke and cannot recover from it.</para>
/// </remarks>
internal sealed class SaveDraftHandler(ICommandBus commandBus, IPeerHelper peerHelper, IMessageEffectAppService messageEffectAppService, IMessageEntityService messageEntityService) : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestSaveDraft, IBool>
{
    protected override async Task<IBool> HandleCoreAsync(IRequestInput input, RequestSaveDraft obj)
    {
        MessageLengthHelper.ValidateMessage(obj.Message);

        var peer = peerHelper.GetPeer(obj.Peer, input.UserId);
        var dialogId = DialogId.Create(input.UserId, peer);

        // A dice has no local form to save: converting it here would roll a value that is then stored
        // in the draft and sent later as a stale outcome. TDLib's can_be_local_message_content is false.
        DiceMediaGuard.ThrowIfDice(obj.Media);

        var (replyToMsgId, hasReplyTarget, topMsgId, savedPeerId) = ParseReplyTo(obj.ReplyTo, input.UserId);

        // "Drafts can be cleared [...] manually by passing empty values to messages.saveDraft".
        // That is how every client drops a cloud draft: TDLib sends an empty message with no media
        // (DraftMessageManager.cpp), Android builds a draftMessageEmpty and sends the same request
        // (MediaDataController.saveDraft). Storing it as a draft instead leaves the other devices
        // holding an empty draftMessage where they expect draftMessageEmpty.
        if (string.IsNullOrEmpty(obj.Message) && obj.Media == null && !hasReplyTarget && obj.SuggestedPost == null)
        {
            await commandBus.PublishAsync(new ClearDraftsCommand(dialogId, input.ToRequestInfo(), input.UserId, peer,
                [new DraftTopic(topMsgId, savedPeerId)]));

            return new TBoolTrue();
        }

        // A draft is never autolinked: the server only generates the autogenerated entities when the
        // text is actually sent. See https://corefork.telegram.org/api/entities
        // ValidateOnly still converts the input-only constructors, so a mention by name does not reach
        // the other devices as inputMessageEntityMentionName, which no client renders.
        var entityResult = await messageEntityService.ProcessAsync(obj.Message, obj.Entities, peer,
            MessageEntityProcessingOptions.ValidateOnly);

        var effect = await messageEffectAppService.ValidateEffectAsync(obj.Effect, input.UserId, peer.PeerType);

        // The media is echoed back to the clients as the InputMedia they sent (draftMessage.media is an
        // InputMedia), so there is nothing to save: registering it on the file server, as this used to
        // do, uploaded and resolved media on every keystroke for a value nothing ever read.
        var draft = new Draft(obj.NoWebpage, obj.InvertMedia, replyToMsgId, obj.Message, CurrentDate,
            entities2: entityResult.Entities,
            topMsgId: topMsgId,
            effect: effect,
            media2: obj.Media,
            replyTo: obj.ReplyTo,
            suggestedPost: obj.SuggestedPost,
            savedPeerId: savedPeerId);

        await commandBus.PublishAsync(new SaveDraftCommand(dialogId, input.ToRequestInfo(), input.UserId, peer, draft));

        return new TBoolTrue();
    }

    /// <summary>
    /// Splits <c>reply_to</c> into the three unrelated things it carries: the message being replied to,
    /// the forum topic the draft belongs to and the monoforum topic it belongs to.
    /// </summary>
    /// <remarks>
    /// A <c>reply_to_msg_id</c> of 0 is not a reply. TDLib clears the draft of a topic by sending
    /// <c>inputReplyToMessage</c> with only <c>top_msg_id</c> filled
    /// (<c>MessageInputReplyTo().get_input_reply_to(...)</c> in <c>SaveDraftMessageQuery</c>), so
    /// treating the presence of <c>reply_to</c> as a reply target would turn every such clear into a
    /// draft that can never be cleared.
    /// </remarks>
    private (int? ReplyToMsgId, bool HasReplyTarget, int? TopMsgId, Peer? SavedPeerId) ParseReplyTo(
        IInputReplyTo? replyTo,
        long selfUserId)
    {
        switch (replyTo)
        {
            case TInputReplyToMessage inputReplyToMessage:
                var replyToMsgId = inputReplyToMessage.ReplyToMsgId > 0
                    ? inputReplyToMessage.ReplyToMsgId
                    : (int?)null;

                return (replyToMsgId,
                    replyToMsgId.HasValue,
                    inputReplyToMessage.TopMsgId is > 0 ? inputReplyToMessage.TopMsgId : null,
                    peerHelper.GetPeer(inputReplyToMessage.MonoforumPeerId, selfUserId));

            case TInputReplyToMonoForum inputReplyToMonoForum:
                return (null, false, null, peerHelper.GetPeer(inputReplyToMonoForum.MonoforumPeerId, selfUserId));

            case TInputReplyToStory:
                return (null, true, null, null);

            case null:
                return (null, false, null, null);

            default:
                throw new ArgumentOutOfRangeException(nameof(replyTo));
        }
    }
}
