// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// Legacy version of messages.forwardMessages (constructor 0x41d41ade)
/// </summary>
[TlObject(0x41d41ade)]
public sealed partial class RequestForwardMessagesLegacy : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x41d41ade;

    public int Flags { get; set; }
    public bool Silent { get; set; }
    public bool Background { get; set; }
    public bool WithMyScore { get; set; }
    public bool DropAuthor { get; set; }
    public bool DropMediaCaptions { get; set; }
    public bool Noforwards { get; set; }
    public MyTelegram.Schema.IInputPeer FromPeer { get; set; }
    public TVector<int> Id { get; set; }
    public TVector<long> RandomId { get; set; }
    public MyTelegram.Schema.IInputPeer ToPeer { get; set; }
    public int? TopMsgId { get; set; }
    public int? ScheduleDate { get; set; }
    public int? ScheduleRepeatPeriod { get; set; }
    public MyTelegram.Schema.IInputPeer? SendAs { get; set; }
    public MyTelegram.Schema.IInputQuickReplyShortcut? QuickReplyShortcut { get; set; }
    public MyTelegram.Schema.IInputReplyTo? ReplyTo { get; set; }
    public int? VideoTimestamp { get; set; }
    public long? AllowPaidStars { get; set; }
    public MyTelegram.Schema.ISuggestedPost? SuggestedPost { get; set; }

    public void ComputeFlag()
    {
        if (Silent) { Flags = Flags.SetBit(5); }
        if (Background) { Flags = Flags.SetBit(6); }
        if (WithMyScore) { Flags = Flags.SetBit(8); }
        if (DropAuthor) { Flags = Flags.SetBit(11); }
        if (DropMediaCaptions) { Flags = Flags.SetBit(12); }
        if (Noforwards) { Flags = Flags.SetBit(14); }
        if (TopMsgId.HasValue) { Flags = Flags.SetBit(9); }
        if (ScheduleDate.HasValue) { Flags = Flags.SetBit(10); }
        if (ScheduleRepeatPeriod.HasValue) { Flags = Flags.SetBit(24); }
        if (SendAs != null) { Flags = Flags.SetBit(13); }
        if (QuickReplyShortcut != null) { Flags = Flags.SetBit(17); }
        if (ReplyTo != null) { Flags = Flags.SetBit(22); }
        if (VideoTimestamp.HasValue) { Flags = Flags.SetBit(20); }
        if (AllowPaidStars.HasValue) { Flags = Flags.SetBit(21); }
        if (SuggestedPost != null) { Flags = Flags.SetBit(23); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(FromPeer);
        writer.Write(Id);
        writer.Write(RandomId);
        writer.Write(ToPeer);
        if (Flags.IsBitSet(9)) { writer.Write(TopMsgId.Value); }
        if (Flags.IsBitSet(10)) { writer.Write(ScheduleDate.Value); }
        if (Flags.IsBitSet(24)) { writer.Write(ScheduleRepeatPeriod.Value); }
        if (Flags.IsBitSet(13)) { writer.Write(SendAs); }
        if (Flags.IsBitSet(17)) { writer.Write(QuickReplyShortcut); }
        if (Flags.IsBitSet(22)) { writer.Write(ReplyTo); }
        if (Flags.IsBitSet(20)) { writer.Write(VideoTimestamp.Value); }
        if (Flags.IsBitSet(21)) { writer.Write(AllowPaidStars.Value); }
        if (Flags.IsBitSet(23)) { writer.Write(SuggestedPost); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(5)) { Silent = true; }
        if (Flags.IsBitSet(6)) { Background = true; }
        if (Flags.IsBitSet(8)) { WithMyScore = true; }
        if (Flags.IsBitSet(11)) { DropAuthor = true; }
        if (Flags.IsBitSet(12)) { DropMediaCaptions = true; }
        if (Flags.IsBitSet(14)) { Noforwards = true; }
        FromPeer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        Id = buffer.Read<TVector<int>>();
        RandomId = buffer.Read<TVector<long>>();
        ToPeer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        if (Flags.IsBitSet(9)) { TopMsgId = buffer.ReadInt32(); }
        if (Flags.IsBitSet(10)) { ScheduleDate = buffer.ReadInt32(); }
        if (Flags.IsBitSet(24)) { ScheduleRepeatPeriod = buffer.ReadInt32(); }
        if (Flags.IsBitSet(13)) { SendAs = buffer.Read<MyTelegram.Schema.IInputPeer>(); }
        if (Flags.IsBitSet(17)) { QuickReplyShortcut = buffer.Read<MyTelegram.Schema.IInputQuickReplyShortcut>(); }
        if (Flags.IsBitSet(22)) { ReplyTo = buffer.Read<MyTelegram.Schema.IInputReplyTo>(); }
        if (Flags.IsBitSet(20)) { VideoTimestamp = buffer.ReadInt32(); }
        if (Flags.IsBitSet(21)) { AllowPaidStars = buffer.ReadInt64(); }
        if (Flags.IsBitSet(23)) { SuggestedPost = buffer.Read<MyTelegram.Schema.ISuggestedPost>(); }
    }
}
