using System.Text;

namespace MyTelegram.Messenger.Services.Translation;

/// <summary>Text plus the entities that survived a translation.</summary>
public sealed record TranslatedText(string Text, TVector<IMessageEntity> Entities);

/// <summary>
/// Carries <a href="https://corefork.telegram.org/api/entities">styled text entities</a> through a
/// translation, which is what Telegram promises Premium users: "the corresponding styled text entities
/// (i.e. correctly repositioned bold, italic, link entities for the translated message)".
///
/// <para>Each entity is encoded as a <c>&lt;span id="N"&gt;</c> and the whole text is sent with DeepL's
/// <c>tag_handling=html</c>, which repositions inline tags around the translated words rather than
/// leaving them where they were. Measured against the live API:
/// <c>&lt;span id="0"&gt;This is &lt;span id="1"&gt;very important&lt;/span&gt; news&lt;/span&gt;</c> comes back as
/// <c>&lt;span id="0"&gt;Это &lt;span id="1"&gt;очень важная&lt;/span&gt; новость&lt;/span&gt;</c> — nesting, ids and
/// the <c>translate="no"</c> attribute all preserved.</para>
///
/// <para>Content that must not be translated (code, a <c>@username</c>, a bare URL, a custom emoji)
/// carries <c>translate="no"</c>, which DeepL's HTML handling honours; verified, including that a
/// quote inside such a span comes back HTML-escaped as <c>&amp;quot;</c>, which is why the decoder
/// unescapes the named references DeepL emits and not just the three it was given.</para>
///
/// <para>Offsets are <b>UTF-16 code units</b>, so every position here is a <c>string</c> index — an
/// emoji outside the BMP is two units, and counting runes instead would shift every entity after it.
/// </para>
/// </summary>
internal interface ITranslationEntityCodec
{
    /// <summary>
    /// The markup to hand the provider. Returns null when the text carries nothing worth encoding, in
    /// which case the caller sends the plain text instead and saves the round trip through HTML.
    /// </summary>
    string? Encode(string text, IReadOnlyList<IMessageEntity>? entities);

    /// <summary>
    /// Turns the provider's answer back into text plus repositioned entities. A response whose markup
    /// cannot be understood degrades to its visible text with no entities rather than throwing: a
    /// mangled decode must not cost the caller the translation, and a bad offset would crash a client.
    /// </summary>
    TranslatedText Decode(string html, IReadOnlyList<IMessageEntity> originalEntities);
}

/// <inheritdoc />
internal sealed class TranslationEntityCodec(ILogger<TranslationEntityCodec> logger)
    : ITranslationEntityCodec, ISingletonDependency
{
    /// <summary>
    /// Entities whose content is not language. Code and pre are the obvious ones; the autogenerated
    /// entities wrap a literal (<c>@durov</c>, a URL, a phone number) that a translator would happily
    /// rewrite; a custom emoji wraps the character that identifies it, and repositioning that is
    /// harmless but translating it is not; and a person's name is not a phrase.
    /// </summary>
    private static bool IsOpaque(IMessageEntity entity)
    {
        return MessageEntityKinds.GetKind(entity) == MessageEntityKind.Pre
               || MessageEntityKinds.IsAutogenerated(entity)
               || entity is TMessageEntityCustomEmoji or TMessageEntityMentionName
                   or TInputMessageEntityMentionName;
    }

    public string? Encode(string text, IReadOnlyList<IMessageEntity>? entities)
    {
        if (string.IsNullOrEmpty(text) || entities == null || entities.Count == 0)
        {
            return null;
        }

        // Dropped entities are never echoed back anyway, so they must not take an id either — the
        // decoder indexes the original list by that id.
        var ordered = entities
            .Select((entity, index) => (entity, index))
            .Where(p => MessageEntityKinds.GetKind(p.entity) != MessageEntityKind.Dropped)
            .Where(p => p.entity.Offset >= 0 && p.entity.Length > 0
                        && p.entity.Offset + p.entity.Length <= text.Length)
            .OrderBy(p => p.entity.Offset)
            .ThenByDescending(p => p.entity.Length)
            .ThenBy(p => MessageEntityKinds.GetPriority(p.entity))
            .ToList();

        if (ordered.Count == 0)
        {
            return null;
        }

        var builder = new StringBuilder(text.Length + ordered.Count * 24);
        var open = new Stack<(int End, int Index)>();
        var next = 0;
        var position = 0;

        while (position <= text.Length)
        {
            // Close everything that ends here, innermost first.
            while (open.Count > 0 && open.Peek().End == position)
            {
                builder.Append("</span>");
                open.Pop();
            }

            // Open everything that starts here. A crossing entity — one that would end after its
            // container — cannot be expressed as nested markup, so it is dropped. The send path runs
            // MessageEntityNormalizer, so this is a repair of something already repaired, not a
            // routine case.
            while (next < ordered.Count && ordered[next].entity.Offset == position)
            {
                var (entity, index) = ordered[next];
                next++;

                var end = entity.Offset + entity.Length;

                if (open.Count > 0 && end > open.Peek().End)
                {
                    logger.LogDebug(
                        "Dropping entity {Type} at {Offset}+{Length} from the translation: it crosses its container",
                        entity.GetType().Name, entity.Offset, entity.Length);

                    continue;
                }

                builder.Append("<span id=\"").Append(index).Append('"');

                if (IsOpaque(entity))
                {
                    builder.Append(" translate=\"no\"");
                }

                builder.Append('>');
                open.Push((end, index));
            }

            if (position == text.Length)
            {
                break;
            }

            AppendEscaped(builder, text[position]);
            position++;
        }

        return builder.ToString();
    }

    private static void AppendEscaped(StringBuilder builder, char c)
    {
        switch (c)
        {
            case '&': builder.Append("&amp;"); break;
            case '<': builder.Append("&lt;"); break;
            case '>': builder.Append("&gt;"); break;
            case '"': builder.Append("&quot;"); break;
            default: builder.Append(c); break;
        }
    }

    public TranslatedText Decode(string html, IReadOnlyList<IMessageEntity> originalEntities)
    {
        var text = new StringBuilder(html.Length);
        var found = new List<(int Index, int Offset, int Length)>();
        var open = new Stack<(int Index, int Start)>();
        var i = 0;
        var malformed = false;

        while (i < html.Length)
        {
            var c = html[i];

            if (c == '<')
            {
                var close = html.IndexOf('>', i + 1);

                if (close < 0)
                {
                    // An unterminated tag: the rest is not markup, so take it as text.
                    malformed = true;
                    text.Append(html, i, html.Length - i);

                    break;
                }

                var tag = html.AsSpan(i + 1, close - i - 1);
                i = close + 1;

                if (tag.StartsWith("/"))
                {
                    if (tag.TrimStart('/').Trim().StartsWith("span", StringComparison.OrdinalIgnoreCase)
                        && open.Count > 0)
                    {
                        var (index, start) = open.Pop();
                        var length = text.Length - start;

                        if (length > 0)
                        {
                            found.Add((index, start, length));
                        }
                    }

                    continue;
                }

                if (tag.StartsWith("span", StringComparison.OrdinalIgnoreCase))
                {
                    var id = ReadSpanId(tag);

                    if (id >= 0 && id < originalEntities.Count)
                    {
                        open.Push((id, text.Length));
                    }
                    else
                    {
                        // An id the provider invented, or a span it added by itself. Push a
                        // placeholder so the matching close tag does not pop somebody else's span.
                        malformed = true;
                        open.Push((-1, text.Length));
                    }
                }

                // Any other tag is markup the provider invented; it is neither text nor an entity.
                continue;
            }

            if (c == '&')
            {
                var semicolon = html.IndexOf(';', i + 1);

                if (semicolon > i && semicolon - i <= 8 && TryUnescape(html.AsSpan(i, semicolon - i + 1), out var value))
                {
                    text.Append(value);
                    i = semicolon + 1;

                    continue;
                }
            }

            text.Append(c);
            i++;
        }

        if (open.Count > 0)
        {
            malformed = true;
        }

        var decoded = text.ToString();

        if (malformed)
        {
            logger.LogWarning(
                "Translated markup did not round-trip cleanly; returning the plain text of {Length} characters without entities",
                decoded.Length);

            return new TranslatedText(decoded, []);
        }

        var entities = new TVector<IMessageEntity>();

        // Keep the first occurrence of each id: a span the provider duplicated is not two entities.
        foreach (var (index, offset, length) in found
                     .GroupBy(p => p.Index)
                     .Select(g => g.OrderBy(p => p.Offset).First())
                     .OrderBy(p => p.Offset)
                     .ThenByDescending(p => p.Length))
        {
            // A TL round trip is the only faithful clone: the original may be a cached read model
            // instance shared with other requests, and every entity type carries different arguments.
            var clone = originalEntities[index].ToBytes().ToTObject<IMessageEntity>();

            if (clone == null)
            {
                continue;
            }

            clone.Offset = offset;
            clone.Length = length;
            entities.Add(clone);
        }

        return new TranslatedText(decoded, entities);
    }

    private static int ReadSpanId(ReadOnlySpan<char> tag)
    {
        var at = tag.IndexOf("id=\"", StringComparison.Ordinal);

        if (at < 0)
        {
            return -1;
        }

        var rest = tag[(at + 4)..];
        var end = rest.IndexOf('"');

        return end > 0 && int.TryParse(rest[..end], out var id) ? id : -1;
    }

    private static bool TryUnescape(ReadOnlySpan<char> reference, out string value)
    {
        value = reference switch
        {
            "&amp;" => "&",
            "&lt;" => "<",
            "&gt;" => ">",
            "&quot;" => "\"",
            "&apos;" => "'",
            "&#39;" => "'",
            "&nbsp;" => " ",
            _ => string.Empty
        };

        return value.Length > 0;
    }
}
