using MyTelegram.Messenger.Services.Entities;
using MyTelegram.Schema;

namespace MyTelegram.Messenger.Tests.Entities;

/// <summary>
/// Covers the entities the server generates itself, per
/// <a href="https://corefork.telegram.org/api/entities#autogenerated-entities">autogenerated entities »</a>.
/// </summary>
public class MessageEntityDetectorTests
{
    private static List<IMessageEntity> Detect(string text, params IMessageEntity[] existing)
    {
        return MessageEntityDetector.Detect(text, existing);
    }

    [Fact]
    public void Url_offset_excludes_the_preceding_space()
    {
        // The regression: a leading-whitespace capture group used to make every URL that is not at
        // position 0 start one character early.
        var entities = Detect("see example.com");

        var url = entities.ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityUrl>();
        url.Offset.ShouldBe(4);
        url.Length.ShouldBe("example.com".Length);
    }

    [Fact]
    public void Url_drops_trailing_sentence_punctuation()
    {
        var entities = Detect("go to https://example.com/a, now");

        var url = entities.ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityUrl>();
        url.Offset.ShouldBe(6);
        url.Length.ShouldBe("https://example.com/a".Length);
    }

    [Fact]
    public void Url_keeps_a_balanced_closing_bracket()
    {
        var entities = Detect("https://en.wikipedia.org/wiki/Foo_(bar)");

        entities.ShouldHaveSingleItem().Length.ShouldBe("https://en.wikipedia.org/wiki/Foo_(bar)".Length);
    }

    [Fact]
    public void Url_drops_an_unbalanced_closing_bracket()
    {
        var entities = Detect("(https://example.com/a)");

        entities.ShouldHaveSingleItem().Length.ShouldBe("https://example.com/a".Length);
    }

    [Fact]
    public void Bare_domain_needs_a_known_top_level_domain()
    {
        Detect("open build.gradle now").ShouldBeEmpty();
        Detect("open notes.txt now").ShouldBeEmpty();
        Detect("open example.dev now").ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityUrl>();

        // Every two-letter suffix is a country code, so "README.md" really is a link — official
        // clients linkify it too.
        Detect("open README.md now").ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityUrl>();
        Detect("open example.ru now").ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityUrl>();
    }

    [Fact]
    public void Email_wins_over_mention_and_url()
    {
        // "@example" used to become a mention and "example.com" a url, on top of the email.
        var entities = Detect("mail me at user@example.com");

        var email = entities.ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityEmail>();
        email.Offset.ShouldBe("mail me at ".Length);
        email.Length.ShouldBe("user@example.com".Length);
    }

    [Fact]
    public void Mention_requires_four_characters_and_a_clean_boundary()
    {
        Detect("hi @abcd").ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityMention>();
        Detect("hi @abc").ShouldBeEmpty();
        Detect("hi mail@abcd").ShouldNotContain(p => p is TMessageEntityMention);
    }

    [Fact]
    public void Bot_command_covers_only_the_token()
    {
        // The regression: the whole message used to be marked as one bot command.
        var entities = Detect("/start@mybot now");

        var command = entities.ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityBotCommand>();
        command.Offset.ShouldBe(0);
        command.Length.ShouldBe("/start@mybot".Length);
    }

    [Fact]
    public void Bot_command_is_found_mid_text()
    {
        var entities = Detect("please run /help");

        var command = entities.ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityBotCommand>();
        command.Offset.ShouldBe("please run ".Length);
        command.Length.ShouldBe("/help".Length);
    }

    [Fact]
    public void Hashtag_needs_a_letter()
    {
        Detect("#tag").ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityHashtag>();
        Detect("#2024").ShouldBeEmpty();
    }

    [Fact]
    public void Cashtag_is_upper_case_only()
    {
        Detect("$USD rate").ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityCashtag>();
        Detect("$usd rate").ShouldBeEmpty();
    }

    [Fact]
    public void Phone_number_needs_a_plus_prefix()
    {
        var entities = Detect("call +1 555 123 4567 now");

        entities.ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityPhone>();
        Detect("call 15551234567 now").ShouldNotContain(p => p is TMessageEntityPhone);
    }

    [Fact]
    public void Bank_card_needs_a_valid_luhn_checksum()
    {
        // 4111 1111 1111 1111 is the canonical Visa test number; flipping a digit breaks Luhn.
        Detect("card 4111111111111111").ShouldContain(p => p is TMessageEntityBankCard);
        Detect("card 4111111111111112").ShouldNotContain(p => p is TMessageEntityBankCard);
    }

    [Fact]
    public void Nothing_is_detected_inside_pre_or_code()
    {
        const string text = "see example.com here";
        var pre = new TMessageEntityPre { Offset = 0, Length = text.Length, Language = string.Empty };

        Detect(text, pre).ShouldBeEmpty();
    }

    [Fact]
    public void Nothing_is_detected_inside_a_manual_link()
    {
        const string text = "see example.com here";
        var textUrl = new TMessageEntityTextUrl
        {
            Offset = 4,
            Length = "example.com".Length,
            Url = "https://elsewhere.example"
        };

        Detect(text, textUrl).ShouldBeEmpty();
    }

    [Fact]
    public void Detection_is_not_confused_by_a_bold_range()
    {
        const string text = "see example.com here";
        var bold = new TMessageEntityBold { Offset = 0, Length = text.Length };

        Detect(text, bold).ShouldHaveSingleItem().ShouldBeOfType<TMessageEntityUrl>();
    }

    [Fact]
    public void Hashtags_are_deduplicated_for_the_search_index()
    {
        var hashtags = MessageEntityDetector.FindHashtags("#one #two #one #2024", 10);

        hashtags.ShouldBe(["one", "two"]);
    }

    [Fact]
    public void Hashtag_indexing_respects_its_cap()
    {
        MessageEntityDetector.FindHashtags("#a1 #b2 #c3 #d4", 2).Count.ShouldBe(2);
    }
}
