// <auto-generated />
using MongoDB.Bson;
using MongoDB.Driver;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Account;
/// <summary>
/// Obtain all <a href="https://corefork.telegram.org/api/themes#chat-themes">chat themes »</a> associated to owned <a href="https://corefork.telegram.org/api/gifts#collectible-gifts">collectible gifts »</a>.
/// <para><c>See <a href="https://corefork.telegram.org/method/account.getUniqueGiftChatThemes"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class GetUniqueGiftChatThemesHandler(IMongoDatabase database) : RpcResultObjectHandler<MyTelegram.Schema.Account.RequestGetUniqueGiftChatThemes, MyTelegram.Schema.Account.IChatThemes>, IObjectHandler
{
    protected override async Task<MyTelegram.Schema.Account.IChatThemes> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Account.RequestGetUniqueGiftChatThemes obj)
    {
        // Query unique star gifts owned by user
        var giftsCol = database.GetCollection<BsonDocument>("saved-star-gifts");
        var filter = Builders<BsonDocument>.Filter.And(
            Builders<BsonDocument>.Filter.Eq("OwnerUserId", input.UserId),
            Builders<BsonDocument>.Filter.Eq("IsUpgraded", true) // Only upgraded gifts have themes
        );

        var giftDocs = await giftsCol.Find(filter).Limit(obj.Limit).ToListAsync();

        var themes = new TVector<MyTelegram.Schema.IChatTheme>();

        // Return empty list - client will then call account.getChatThemes for regular themes

        return new MyTelegram.Schema.Account.TChatThemes
        {
            Hash = 0,
            Themes = themes,
            Chats = new TVector<MyTelegram.Schema.IChat>(),
            Users = new TVector<MyTelegram.Schema.IUser>()
        };
    }
}