using MyTelegram.Schema;

namespace MyTelegram.Messenger.Services.Entities;

/// <summary>How a text's entities should be treated on the way in.</summary>
public sealed record MessageEntityProcessingOptions
{
    /// <summary>
    /// Whether the server should generate the autogenerated entity types for this text. Off for
    /// texts the server does not autolink, such as drafts, poll options and bot-supplied captions.
    /// </summary>
    public bool Autodetect { get; init; } = true;

    /// <summary>
    /// Whether the user is allowed to apply formatting by hand. Off when <c>stories_entities</c>
    /// denies styled captions to this account; the autogenerated entities are kept either way.
    /// </summary>
    public bool AllowManualEntities { get; init; } = true;

    /// <summary>Whether to resolve the users mentioned by the text. Only the send path needs this.</summary>
    public bool ResolveMentionedUsers { get; init; } = true;

    public static readonly MessageEntityProcessingOptions Default = new();

    /// <summary>Validation and normalisation only — no autolinking, no mention resolution.</summary>
    public static readonly MessageEntityProcessingOptions ValidateOnly = new()
    {
        Autodetect = false,
        ResolveMentionedUsers = false
    };
}

/// <summary>
/// The processed entities, plus the users the text mentions. Mentioned users drive the unread
/// mention badge, so they are resolved from the final entity list rather than from a second scan.
/// </summary>
public sealed record MessageEntityProcessingResult(
    TVector<IMessageEntity>? Entities,
    List<long> MentionedUserIds)
{
    public static readonly MessageEntityProcessingResult Empty = new(null, []);
}

/// <summary>
/// The single entry point for everything to do with
/// <a href="https://corefork.telegram.org/api/entities">styled text</a>: validation, conversion of
/// the input-only constructors, custom emoji checks, server-side autolinking and nesting repair.
/// Every surface that accepts entities from a client goes through this.
/// </summary>
public interface IMessageEntityService
{
    Task<MessageEntityProcessingResult> ProcessAsync(
        string? text,
        IEnumerable<IMessageEntity>? entities,
        Peer? toPeer = null,
        MessageEntityProcessingOptions? options = null);

    /// <summary>
    /// Validates and normalises without touching the database. For surfaces where entities are
    /// stored verbatim and no custom emoji or mention resolution is possible.
    /// </summary>
    TVector<IMessageEntity>? ValidateAndNormalize(string? text, IEnumerable<IMessageEntity>? entities);

    /// <summary>The hashtags of a text, as indexed for hashtag search.</summary>
    List<string> GetHashtags(string? text);
}
