using MyTelegram.Schema;

namespace MyTelegram.Messenger.Services.Entities;

/// <summary>
/// Structural classification of a message entity. The nesting rules of
/// <a href="https://corefork.telegram.org/api/entities">styled text</a> are expressed in terms of
/// these groups rather than of concrete constructors, exactly the way tdlib groups them in
/// <c>td/telegram/MessageEntity.cpp</c> (<c>get_splittable_entities_mask</c> and friends).
/// </summary>
internal enum MessageEntityKind
{
    /// <summary>Never stored and never echoed back: <c>messageEntityUnknown</c> and the diff entities.</summary>
    Dropped,

    /// <summary>Bold, italic, underline, strikethrough, spoiler — may be split at a container boundary.</summary>
    Splittable,

    /// <summary>Code and pre — cannot contain anything, cannot be contained by anything but a blockquote.</summary>
    Pre,

    /// <summary>Everything clickable: mentions, links, custom emoji, formatted dates.</summary>
    Continuous,

    /// <summary>Blockquote — contains anything except another blockquote.</summary>
    Blockquote
}

internal static class MessageEntityKinds
{
    public static MessageEntityKind GetKind(IMessageEntity entity)
    {
        return entity switch
        {
            TMessageEntityBold or TMessageEntityItalic or TMessageEntityUnderline or TMessageEntityStrike
                or TMessageEntitySpoiler => MessageEntityKind.Splittable,

            TMessageEntityCode or TMessageEntityPre => MessageEntityKind.Pre,

            TMessageEntityBlockquote => MessageEntityKind.Blockquote,

            TMessageEntityMention or TMessageEntityHashtag or TMessageEntityCashtag or TMessageEntityBotCommand
                or TMessageEntityUrl or TMessageEntityEmail or TMessageEntityPhone or TMessageEntityBankCard
                or TMessageEntityTextUrl or TMessageEntityMentionName or TInputMessageEntityMentionName
                or TMessageEntityCustomEmoji or TMessageEntityFormattedDate => MessageEntityKind.Continuous,

            _ => MessageEntityKind.Dropped
        };
    }

    /// <summary>
    /// Whether the server, not the user, produces this entity. Autogenerated entities are re-derived
    /// from the text on every send and edit, so a client-supplied copy is redundant.
    /// See https://corefork.telegram.org/api/entities#autogenerated-entities
    /// </summary>
    public static bool IsAutogenerated(IMessageEntity entity)
    {
        return entity is TMessageEntityMention or TMessageEntityHashtag or TMessageEntityCashtag
            or TMessageEntityBotCommand or TMessageEntityUrl or TMessageEntityEmail or TMessageEntityPhone
            or TMessageEntityBankCard;
    }

    /// <summary>
    /// Whether the entity carries formatting the user applied by hand. This is what
    /// <c>stories_entities</c> gates for non-premium accounts.
    /// See https://corefork.telegram.org/api/entities#manual-entities
    /// </summary>
    public static bool IsManual(IMessageEntity entity)
    {
        return GetKind(entity) != MessageEntityKind.Dropped && !IsAutogenerated(entity);
    }

    /// <summary>
    /// Tie-breaker for entities that start at the same offset and have the same length. Containers
    /// have to be sorted before their content, otherwise the nesting walk sees the child first.
    /// </summary>
    public static int GetPriority(IMessageEntity entity)
    {
        return GetKind(entity) switch
        {
            MessageEntityKind.Blockquote => 0,
            MessageEntityKind.Pre => 1,
            MessageEntityKind.Continuous => 2,
            MessageEntityKind.Splittable => 3,
            _ => 4
        };
    }

    /// <summary>
    /// Two entities are the same when they have the same constructor, the same range and the same
    /// arguments. Used to drop the duplicates clients send back after an edit.
    /// </summary>
    public static bool AreEquivalent(IMessageEntity left, IMessageEntity right)
    {
        if (left.ConstructorId != right.ConstructorId || left.Offset != right.Offset ||
            left.Length != right.Length)
        {
            return false;
        }

        return (left, right) switch
        {
            (TMessageEntityTextUrl a, TMessageEntityTextUrl b) =>
                string.Equals(a.Url, b.Url, StringComparison.Ordinal),
            (TMessageEntityPre a, TMessageEntityPre b) =>
                string.Equals(a.Language, b.Language, StringComparison.Ordinal),
            (TMessageEntityMentionName a, TMessageEntityMentionName b) => a.UserId == b.UserId,
            (TMessageEntityCustomEmoji a, TMessageEntityCustomEmoji b) => a.DocumentId == b.DocumentId,
            (TMessageEntityBlockquote a, TMessageEntityBlockquote b) => a.Collapsed == b.Collapsed,
            _ => true
        };
    }

    /// <summary>
    /// Copies an entity onto a different range, keeping every argument. Only ever used for the
    /// splittable entities, which are the only ones the normaliser is allowed to cut in two.
    /// </summary>
    public static IMessageEntity CloneWithRange(IMessageEntity entity, int offset, int length)
    {
        IMessageEntity clone = entity switch
        {
            TMessageEntityBold => new TMessageEntityBold(),
            TMessageEntityItalic => new TMessageEntityItalic(),
            TMessageEntityUnderline => new TMessageEntityUnderline(),
            TMessageEntityStrike => new TMessageEntityStrike(),
            TMessageEntitySpoiler => new TMessageEntitySpoiler(),
            _ => throw new ArgumentOutOfRangeException(nameof(entity), entity.GetType().Name,
                "Only splittable entities may be cloned onto a different range")
        };

        clone.Offset = offset;
        clone.Length = length;

        return clone;
    }
}
