using MongoDB.Bson;
using MongoDB.Driver;
using MyTelegram.Messenger.Helpers;
using MyTelegram.Schema;

namespace MyTelegram.Messenger.Services.Entities;

/// <inheritdoc cref="IMessageEntityService"/>
public class MessageEntityService(
    IMongoDatabase mongoDatabase,
    IPeerHelper peerHelper,
    IUserAppService userAppService,
    IQueryProcessor queryProcessor)
    : IMessageEntityService, ITransientDependency
{
    /// <summary>How many hashtags of a text are indexed for search.</summary>
    private const int MaxIndexedHashtags = 10;

    public async Task<MessageEntityProcessingResult> ProcessAsync(
        string? text,
        IEnumerable<IMessageEntity>? entities,
        Peer? toPeer = null,
        MessageEntityProcessingOptions? options = null)
    {
        options ??= MessageEntityProcessingOptions.Default;

        var working = entities?.ToList() ?? [];
        MessageEntityValidator.Validate(text, working);

        if (string.IsNullOrEmpty(text))
        {
            // Entities cannot describe a range of an empty text. A media message with no caption
            // legitimately arrives here with an empty entity list.
            return MessageEntityProcessingResult.Empty;
        }

        await ConvertInputMentionNamesAsync(working);
        await ProcessCustomEmojiAsync(text, working);

        if (!options.AllowManualEntities)
        {
            working.RemoveAll(MessageEntityKinds.IsManual);
        }

        if (options.Autodetect)
        {
            // The server owns the autogenerated types: a copy sent by the client is dropped and
            // regenerated. Without this, every edit round-trip would double them, because clients
            // send back the entities they were given.
            working.RemoveAll(MessageEntityKinds.IsAutogenerated);
            working.AddRange(MessageEntityDetector.Detect(text, working));
        }

        var normalized = MessageEntityNormalizer.Normalize(text, working);

        var mentionedUserIds = options.ResolveMentionedUsers && toPeer != null
            ? await ResolveMentionedUsersAsync(text, normalized, toPeer)
            : [];

        return new MessageEntityProcessingResult(
            normalized.Count > 0 ? new TVector<IMessageEntity>(normalized) : null,
            mentionedUserIds);
    }

    public TVector<IMessageEntity>? ValidateAndNormalize(string? text, IEnumerable<IMessageEntity>? entities)
    {
        var working = entities?.ToList() ?? [];
        MessageEntityValidator.Validate(text, working);

        if (string.IsNullOrEmpty(text))
        {
            return null;
        }

        var normalized = MessageEntityNormalizer.Normalize(text, working);

        return normalized.Count > 0 ? new TVector<IMessageEntity>(normalized) : null;
    }

    public List<string> GetHashtags(string? text)
    {
        return MessageEntityDetector.FindHashtags(text, MaxIndexedHashtags);
    }

    /// <summary>
    /// <c>inputMessageEntityMentionName</c> is an input-only constructor: it must be turned into
    /// <c>messageEntityMentionName</c> before the entity is stored, otherwise clients receive a
    /// constructor they refuse to render and the mention silently loses its link.
    /// </summary>
    private async Task ConvertInputMentionNamesAsync(List<IMessageEntity> entities)
    {
        for (var i = 0; i < entities.Count; i++)
        {
            if (entities[i] is not TInputMessageEntityMentionName input)
            {
                continue;
            }

            Peer peer;
            try
            {
                peer = peerHelper.GetPeer(input.UserId);
            }
            catch (Exception)
            {
                RpcErrors.RpcErrors400.EntityMentionUserInvalid.ThrowRpcError();
                return;
            }

            if (peer.PeerType != PeerType.User || peer.PeerId <= 0)
            {
                RpcErrors.RpcErrors400.EntityMentionUserInvalid.ThrowRpcError();
            }

            var user = await userAppService.GetAsync(peer.PeerId);
            if (user == null || user.IsDeleted == true)
            {
                RpcErrors.RpcErrors400.EntityMentionUserInvalid.ThrowRpcError();
            }

            entities[i] = new TMessageEntityMentionName
            {
                Offset = input.Offset,
                Length = input.Length,
                UserId = peer.PeerId
            };
        }
    }

    private async Task ProcessCustomEmojiAsync(string message, List<IMessageEntity> entities)
    {
        var customEmojiEntities = entities.OfType<TMessageEntityCustomEmoji>().ToList();
        if (customEmojiEntities.Count == 0)
        {
            return;
        }

        var docCol = mongoDatabase.GetCollection<BsonDocument>("eventflow-documentreadmodel");
        var documentIds = customEmojiEntities.Select(x => x.DocumentId).Distinct().ToList();
        var filter = Builders<BsonDocument>.Filter.In("DocumentId", documentIds.Select(x => (BsonValue)new BsonInt64(x)));
        var documents = await docCol.Find(filter).ToListAsync();
        var documentMap = documents.ToDictionary(x => x["DocumentId"].ToInt64());

        foreach (var entity in customEmojiEntities)
        {
            if (!documentMap.TryGetValue(entity.DocumentId, out var document))
            {
                RpcErrors.RpcErrors400.DocumentInvalid.ThrowRpcError();
            }

            if (!TryGetCustomEmojiAttributeForEntity(document!, out var attribute))
            {
                if (await TryDowngradeLegacyAnimatedEmojiEntityAsync(message, entities, entity))
                {
                    continue;
                }

                RpcErrors.RpcErrors400.DocumentInvalid.ThrowRpcError();
            }

            var text = message.Substring(entity.Offset, entity.Length);
            if (IsSameEmoji(text, attribute.Alt))
            {
                continue;
            }

            var replacement = await TryResolveReplacementCustomEmojiDocumentAsync(text, attribute);
            if (replacement != null)
            {
                entity.DocumentId = replacement.Value;
                continue;
            }

            RpcErrors.RpcErrors400.EmoticonInvalid.ThrowRpcError();
        }
    }

    private async Task<bool> TryDowngradeLegacyAnimatedEmojiEntityAsync(
        string message,
        List<IMessageEntity> entities,
        TMessageEntityCustomEmoji entity)
    {
        var setCol = mongoDatabase.GetCollection<BsonDocument>("eventflow-stickersetreadmodel");
        var setDoc = await setCol.Find(Builders<BsonDocument>.Filter.Eq("ShortName", "AnimatedEmojies"))
            .FirstOrDefaultAsync();
        if (setDoc == null || !setDoc.Contains("Packs") || !setDoc["Packs"].IsBsonArray)
        {
            return false;
        }

        var text = message.Substring(entity.Offset, entity.Length);
        var belongsToLegacyAnimatedEmojiSet = setDoc["Packs"].AsBsonArray
            .Where(x => x.IsBsonDocument)
            .Select(x => x.AsBsonDocument)
            .Any(x =>
                x.Contains("Emoticon") &&
                x["Emoticon"].IsString &&
                IsSameEmoji(text, x["Emoticon"].AsString) &&
                x.Contains("Documents") &&
                x["Documents"].IsBsonArray &&
                x["Documents"].AsBsonArray.Any(documentId => documentId.ToInt64() == entity.DocumentId));

        if (!belongsToLegacyAnimatedEmojiSet)
        {
            return false;
        }

        entities.Remove(entity);

        return true;
    }

    private async Task<long?> TryResolveReplacementCustomEmojiDocumentAsync(
        string text,
        TDocumentAttributeCustomEmoji attribute)
    {
        if (attribute.Stickerset is not TInputStickerSetID stickerSetId || stickerSetId.Id == 0)
        {
            return null;
        }

        var setCol = mongoDatabase.GetCollection<BsonDocument>("eventflow-stickersetreadmodel");
        var setDoc = await setCol.Find(Builders<BsonDocument>.Filter.Eq("StickerSetId", stickerSetId.Id))
            .FirstOrDefaultAsync();
        if (setDoc == null || !setDoc.Contains("Packs") || !setDoc["Packs"].IsBsonArray)
        {
            return null;
        }

        var candidateDocumentIds = setDoc["Packs"].AsBsonArray
            .Where(x => x.IsBsonDocument)
            .Select(x => x.AsBsonDocument)
            .Where(x => x.Contains("Emoticon") && x["Emoticon"].IsString && IsSameEmoji(text, x["Emoticon"].AsString))
            .Where(x => x.Contains("Documents") && x["Documents"].IsBsonArray)
            .SelectMany(x => x["Documents"].AsBsonArray)
            .Select(x => x.ToInt64())
            .Distinct()
            .ToList();

        if (candidateDocumentIds.Count == 0)
        {
            return null;
        }

        var docCol = mongoDatabase.GetCollection<BsonDocument>("eventflow-documentreadmodel");
        var filter = Builders<BsonDocument>.Filter.In("DocumentId",
            candidateDocumentIds.Select(x => (BsonValue)new BsonInt64(x)));
        var docs = await docCol.Find(filter).ToListAsync();
        foreach (var candidateDocumentId in candidateDocumentIds)
        {
            var candidate = docs.FirstOrDefault(x => x["DocumentId"].ToInt64() == candidateDocumentId);
            if (candidate != null &&
                TryGetCustomEmojiAttributeForEntity(candidate, out var candidateAttribute) &&
                IsSameEmoji(text, candidateAttribute.Alt))
            {
                return candidateDocumentId;
            }
        }

        return null;
    }

    private static bool TryGetCustomEmojiAttributeForEntity(BsonDocument document,
        out TDocumentAttributeCustomEmoji attribute)
    {
        return CustomEmojiAttributeHelper.TryGetCustomEmojiAttribute(document, out attribute) ||
               CustomEmojiAttributeHelper.TryGetStickerAttributeAsCustomEmoji(document, out attribute);
    }

    private static bool IsSameEmoji(string? left, string? right)
    {
        if (string.IsNullOrEmpty(left) || string.IsNullOrEmpty(right))
        {
            return false;
        }

        return string.Equals(NormalizeEmoji(left), NormalizeEmoji(right), StringComparison.Ordinal);
    }

    private static string NormalizeEmoji(string value)
    {
        return value.Replace("️", string.Empty, StringComparison.Ordinal);
    }

    /// <summary>
    /// Works out who the text mentions, from the final entity list. A mention only counts when the
    /// mentioned user can actually open the chat, so the candidates are filtered by peer type.
    /// </summary>
    private async Task<List<long>> ResolveMentionedUsersAsync(
        string message,
        List<IMessageEntity> entities,
        Peer toPeer)
    {
        var mentionedUserNames = new List<string>();
        var mentionedUserIds = new List<long>();

        foreach (var entity in entities)
        {
            switch (entity)
            {
                case TMessageEntityMention mention when mention.Length > 1:
                    mentionedUserNames.Add(message.Substring(mention.Offset + 1, mention.Length - 1));
                    break;
                case TMessageEntityMentionName mentionName:
                    mentionedUserIds.Add(mentionName.UserId);
                    break;
            }
        }

        if (mentionedUserNames.Count > 0)
        {
            var mentionedUsers =
                await queryProcessor.ProcessAsync(new GetUserNameListByNamesQuery(mentionedUserNames, PeerType.User));
            mentionedUserIds.AddRange(mentionedUsers.Select(p => p.PeerId).Distinct());
        }

        if (mentionedUserIds.Count == 0)
        {
            return [];
        }

        switch (toPeer.PeerType)
        {
            case PeerType.Channel:
                // Only members can be mentioned: a badge in a chat the user cannot open is a dead end.
                var memberUserIds =
                    await queryProcessor.ProcessAsync(new GetChannelMemberIdListQuery(toPeer.PeerId, mentionedUserIds));
                return memberUserIds.ToList();

            // In a private chat the only person who can be mentioned is the other party; naming a third
            // user is just text. Clients do count mentions here — tdlib bumps unread_mention_count for
            // every dialog type, and Android calls messages.readMentions for private chats too.
            case PeerType.User:
                return mentionedUserIds.Contains(toPeer.PeerId) ? [toPeer.PeerId] : [];

            // Legacy basic chats have no member read model in this fork, so membership cannot be
            // verified and no mention is recorded.
            default:
                return [];
        }
    }
}
