using System.Text.RegularExpressions;
using MyTelegram.Schema;

namespace MyTelegram.Messenger.Services.Entities;

/// <summary>
/// Produces the entities the server, not the user, is responsible for: mentions, hashtags, cashtags,
/// bot commands, URLs, e-mail addresses, phone numbers and bank cards. Clients rely on this so they
/// do not have to implement autolinking themselves.
/// See https://corefork.telegram.org/api/entities#autogenerated-entities
/// <para>
/// The scanners follow tdlib's <c>find_mentions</c> / <c>find_hashtags</c> / <c>find_cashtags</c> /
/// <c>find_bot_commands</c> / <c>find_urls</c> / <c>is_email_address</c> / <c>find_phone_numbers</c> /
/// <c>find_bank_card_numbers</c> in <c>td/telegram/MessageEntity.cpp</c>.
/// </para>
/// </summary>
internal static partial class MessageEntityDetector
{
    [GeneratedRegex(@"(?<![\w@/+.\-])@([A-Za-z0-9_]{4,32})(?![A-Za-z0-9_])", RegexOptions.CultureInvariant)]
    private static partial Regex MentionRegex();

    [GeneratedRegex(@"(?<![\w#])#([\p{L}\p{N}_]{1,255})(?:@([A-Za-z0-9_]{3,32}))?(?![\p{L}\p{N}_#])",
        RegexOptions.CultureInvariant)]
    private static partial Regex HashtagRegex();

    [GeneratedRegex(@"(?<![\w$])\$([A-Z]{1,8})(?:@([A-Za-z0-9_]{3,32}))?(?![A-Za-z0-9_$])",
        RegexOptions.CultureInvariant)]
    private static partial Regex CashtagRegex();

    [GeneratedRegex(@"(?<![\w/<>@])/([A-Za-z0-9_]{1,64})(?:@([A-Za-z0-9_]{3,32}))?(?![A-Za-z0-9_/])",
        RegexOptions.CultureInvariant)]
    private static partial Regex BotCommandRegex();

    /// <summary>
    /// tdlib's <c>is_email_address</c> regex, anchored on word boundaries instead of on the whole
    /// string: <c>^([a-z0-9_-]{0,26}[.+]){0,10}[a-z0-9_-]{1,35}@(([a-z0-9][a-z0-9_-]{0,28})?[a-z0-9][.]){1,6}[a-z]{2,8}$</c>
    /// </summary>
    [GeneratedRegex(
        @"(?<![\w.+\-@])(?:[A-Za-z0-9_\-]{0,26}[.+]){0,10}[A-Za-z0-9_\-]{1,35}@(?:(?:[A-Za-z0-9][A-Za-z0-9_\-]{0,28})?[A-Za-z0-9]\.){1,6}[A-Za-z]{2,8}(?![A-Za-z0-9.\-])",
        RegexOptions.CultureInvariant | RegexOptions.IgnoreCase)]
    private static partial Regex EmailRegex();

    [GeneratedRegex(
        @"(?<![\w@.\-/])(?:(?:https?|ftp|tg|sftp|ton|tonsite)://[^\s<>""]+|(?<host>(?:[A-Za-z0-9](?:[A-Za-z0-9\-_]{0,61}[A-Za-z0-9])?\.)+(?<tld>[A-Za-z]{2,24}))(?::\d{1,5})?(?:[/?#][^\s<>""]*)?)",
        RegexOptions.CultureInvariant)]
    private static partial Regex UrlRegex();

    [GeneratedRegex(@"(?<![\w+])\+\d(?:[ \-().]{0,2}\d){6,17}", RegexOptions.CultureInvariant)]
    private static partial Regex PhoneRegex();

    /// <summary>
    /// Generic top-level domains a schemeless <c>domain.tld</c> is linkified for. Every two-letter TLD
    /// is a country code and is accepted without being listed. Without this check every
    /// <c>README.md</c> or <c>build.gradle</c> in a code discussion would turn blue.
    /// </summary>
    private static readonly HashSet<string> CommonTopLevelDomains = new(StringComparer.OrdinalIgnoreCase)
    {
        "com", "net", "org", "edu", "gov", "mil", "int", "arpa", "info", "biz", "name", "pro", "aero",
        "coop", "museum", "jobs", "mobi", "travel", "tel", "asia", "cat", "post", "xxx",
        "app", "art", "bar", "best", "bid", "blog", "buzz", "cafe", "cash", "chat", "city", "click",
        "cloud", "club", "codes", "dev", "design", "digital", "download", "email", "energy", "expert",
        "fans", "farm", "film", "fit", "fun", "fund", "gallery", "games", "gift", "gold", "group",
        "guru", "help", "host", "house", "icu", "ink", "land", "law", "life", "link", "live", "ltd",
        "market", "media", "money", "movie", "network", "news", "ninja", "one", "online", "page",
        "party", "photo", "pics", "pizza", "place", "plus", "press", "pub", "red", "rent", "rest",
        "review", "rocks", "run", "sale", "school", "science", "services", "shop", "show", "site",
        "social", "software", "solutions", "space", "store", "studio", "style", "support", "systems",
        "team", "tech", "tips", "today", "top", "tours", "town", "trade", "video", "vip", "watch",
        "webcam", "website", "wiki", "work", "world", "wtf", "xyz", "zone"
    };

    /// <summary>
    /// Returns the entities the server generates for <paramref name="text"/>, skipping every range
    /// already claimed by <paramref name="existing"/>. A section inside <c>pre</c>/<c>code</c> or
    /// inside a link the user created by hand is never autolinked.
    /// </summary>
    public static List<IMessageEntity> Detect(string? text, IReadOnlyList<IMessageEntity>? existing)
    {
        var detected = new List<IMessageEntity>();
        if (string.IsNullOrEmpty(text))
        {
            return detected;
        }

        var claimed = BuildClaimedMask(text.Length, existing);

        DetectRegex(text, claimed, detected, EmailRegex(), (o, l) => new TMessageEntityEmail { Offset = o, Length = l });
        DetectUrls(text, claimed, detected);
        DetectRegex(text, claimed, detected, PhoneRegex(), (o, l) => new TMessageEntityPhone { Offset = o, Length = l });
        DetectBankCards(text, claimed, detected);
        DetectRegex(text, claimed, detected, MentionRegex(),
            (o, l) => new TMessageEntityMention { Offset = o, Length = l });
        DetectHashtags(text, claimed, detected);
        DetectRegex(text, claimed, detected, CashtagRegex(),
            (o, l) => new TMessageEntityCashtag { Offset = o, Length = l });
        DetectRegex(text, claimed, detected, BotCommandRegex(),
            (o, l) => new TMessageEntityBotCommand { Offset = o, Length = l });

        detected.Sort((left, right) => left.Offset.CompareTo(right.Offset));

        return detected;
    }

    /// <summary>
    /// The hashtags of a text, normalised the way the search index stores them. Shares the scanner
    /// with <see cref="Detect"/> so an indexed hashtag is always one the client renders as a link.
    /// </summary>
    public static List<string> FindHashtags(string? text, int max)
    {
        var hashtags = new List<string>();
        if (string.IsNullOrEmpty(text))
        {
            return hashtags;
        }

        foreach (Match match in HashtagRegex().Matches(text))
        {
            if (hashtags.Count >= max)
            {
                break;
            }

            var tag = match.Groups[1].Value;
            if (!HasLetter(tag) || hashtags.Contains(tag))
            {
                continue;
            }

            hashtags.Add(tag);
        }

        return hashtags;
    }

    private static bool[] BuildClaimedMask(int length, IReadOnlyList<IMessageEntity>? existing)
    {
        var claimed = new bool[length];
        if (existing == null)
        {
            return claimed;
        }

        foreach (var entity in existing)
        {
            var kind = MessageEntityKinds.GetKind(entity);
            if (kind != MessageEntityKind.Pre && kind != MessageEntityKind.Continuous)
            {
                continue;
            }

            var start = Math.Max(0, entity.Offset);
            var end = Math.Min(length, entity.Offset + entity.Length);
            for (var i = start; i < end; i++)
            {
                claimed[i] = true;
            }
        }

        return claimed;
    }

    private static void DetectRegex(
        string text,
        bool[] claimed,
        List<IMessageEntity> detected,
        Regex regex,
        Func<int, int, IMessageEntity> factory)
    {
        foreach (Match match in regex.Matches(text))
        {
            TryAdd(claimed, detected, match.Index, match.Length, factory);
        }
    }

    private static void DetectHashtags(string text, bool[] claimed, List<IMessageEntity> detected)
    {
        foreach (Match match in HashtagRegex().Matches(text))
        {
            // tdlib refuses a hashtag made of digits only.
            if (!HasLetter(match.Groups[1].Value))
            {
                continue;
            }

            TryAdd(claimed, detected, match.Index, match.Length,
                (o, l) => new TMessageEntityHashtag { Offset = o, Length = l });
        }
    }

    private static void DetectUrls(string text, bool[] claimed, List<IMessageEntity> detected)
    {
        foreach (Match match in UrlRegex().Matches(text))
        {
            var tld = match.Groups["tld"];

            // A schemeless match is only a link when its top-level domain looks like one.
            if (tld.Success && tld.Length != 2 && !CommonTopLevelDomains.Contains(tld.Value))
            {
                continue;
            }

            var length = TrimUrl(text, match.Index, match.Length);
            if (length <= 0)
            {
                continue;
            }

            TryAdd(claimed, detected, match.Index, length, (o, l) => new TMessageEntityUrl { Offset = o, Length = l });
        }
    }

    /// <summary>
    /// Drops the sentence punctuation a URL at the end of a sentence picks up, and the closing
    /// bracket of a URL written inside brackets.
    /// </summary>
    private static int TrimUrl(string text, int offset, int length)
    {
        while (length > 0)
        {
            var last = text[offset + length - 1];
            if (last is '.' or ',' or ';' or ':' or '!' or '?' or '\'' or '"' or '*' or '_' or '~')
            {
                length--;
                continue;
            }

            if (last is ')' or ']' or '}' or '>')
            {
                var open = last switch
                {
                    ')' => '(',
                    ']' => '[',
                    '}' => '{',
                    _ => '<'
                };

                var balance = 0;
                for (var i = 0; i < length; i++)
                {
                    var c = text[offset + i];
                    if (c == open)
                    {
                        balance++;
                    }
                    else if (c == last)
                    {
                        balance--;
                    }
                }

                if (balance < 0)
                {
                    length--;
                    continue;
                }
            }

            break;
        }

        return length;
    }

    private static void DetectBankCards(string text, bool[] claimed, List<IMessageEntity> detected)
    {
        var index = 0;
        while (index < text.Length)
        {
            if (!char.IsAsciiDigit(text[index]))
            {
                index++;
                continue;
            }

            if (index > 0 && (char.IsLetterOrDigit(text[index - 1]) || text[index - 1] is '+' or '.' or '-' or '_'))
            {
                index++;
                continue;
            }

            var end = index;
            var digitCount = 0;
            var lastDigitEnd = index;
            while (end < text.Length)
            {
                var c = text[end];
                if (char.IsAsciiDigit(c))
                {
                    digitCount++;
                    end++;
                    lastDigitEnd = end;
                    continue;
                }

                // A single space or dash may separate groups of digits, nothing else.
                if ((c == ' ' || c == '-') && end + 1 < text.Length && char.IsAsciiDigit(text[end + 1]))
                {
                    end++;
                    continue;
                }

                break;
            }

            if (digitCount is >= 13 and <= 19 &&
                (lastDigitEnd == text.Length || !char.IsLetter(text[lastDigitEnd])) &&
                IsValidBankCard(text, index, lastDigitEnd, digitCount))
            {
                TryAdd(claimed, detected, index, lastDigitEnd - index,
                    (o, l) => new TMessageEntityBankCard { Offset = o, Length = l });
            }

            index = Math.Max(lastDigitEnd, index + 1);
        }
    }

    /// <summary>Luhn checksum plus the issuer length rules, mirroring tdlib's <c>is_valid_bank_card</c>.</summary>
    private static bool IsValidBankCard(string text, int start, int end, int digitCount)
    {
        Span<int> digits = stackalloc int[19];
        var count = 0;
        for (var i = start; i < end && count < digits.Length; i++)
        {
            if (char.IsAsciiDigit(text[i]))
            {
                digits[count++] = text[i] - '0';
            }
        }

        var sum = 0;
        for (var i = count; i > 0; i--)
        {
            var digit = digits[i - 1];
            if ((count - i) % 2 == 0)
            {
                sum += digit;
            }
            else
            {
                sum += digit < 5 ? 2 * digit : 2 * digit - 9;
            }
        }

        if (sum % 10 != 0)
        {
            return false;
        }

        var prefix1 = digits[0];
        var prefix2 = prefix1 * 10 + digits[1];
        var prefix3 = prefix2 * 10 + digits[2];
        var prefix4 = prefix3 * 10 + digits[3];

        if (prefix1 == 4)
        {
            // Visa
            return digitCount is 13 or 16 or 18 or 19;
        }

        if (prefix2 is >= 51 and <= 55 || prefix4 is >= 2221 and <= 2720)
        {
            // Mastercard
            return digitCount == 16;
        }

        if (prefix2 is 34 or 37)
        {
            // American Express
            return digitCount == 15;
        }

        if (prefix2 is 62 or 81)
        {
            // UnionPay
            return digitCount is >= 16 and <= 19;
        }

        if (prefix3 is >= 300 and <= 305 || prefix2 is 36 or 38)
        {
            // Diners Club
            return digitCount == 14;
        }

        if (prefix4 is >= 2200 and <= 2204)
        {
            // MIR
            return digitCount == 16;
        }

        return true;
    }

    private static void TryAdd(
        bool[] claimed,
        List<IMessageEntity> detected,
        int offset,
        int length,
        Func<int, int, IMessageEntity> factory)
    {
        for (var i = offset; i < offset + length; i++)
        {
            if (claimed[i])
            {
                return;
            }
        }

        for (var i = offset; i < offset + length; i++)
        {
            claimed[i] = true;
        }

        detected.Add(factory(offset, length));
    }

    private static bool HasLetter(string value)
    {
        foreach (var c in value)
        {
            if (char.IsLetter(c))
            {
                return true;
            }
        }

        return false;
    }
}
