// <auto-generated />
using MongoDB.Driver;
using MyTelegram.Messenger.Services.Phone;
using MyTelegram.Schema;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Phone;
/// <summary>
/// Possible errors
/// Code Type Description
/// 400 GROUPCALL_INVALID The specified group call is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/phone.sendGroupCallEncryptedMessage"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class SendGroupCallEncryptedMessageHandler(
    IMongoDatabase mongoDatabase,
    IObjectMessageSender objectMessageSender)
    : RpcResultObjectHandler<MyTelegram.Schema.Phone.RequestSendGroupCallEncryptedMessage, IBool>, IObjectHandler
{
    private readonly IMongoCollection<GroupCallDocument> _groupCallCollection =
        mongoDatabase.GetCollection<GroupCallDocument>("group_calls");

    protected override async Task<IBool> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Phone.RequestSendGroupCallEncryptedMessage obj)
    {
        var groupCall = await _groupCallCollection.Find(GroupCallStateHelper.Filter(obj.Call, input.UserId)).FirstOrDefaultAsync();
        if (groupCall == null || !groupCall.Conference || !groupCall.Active)
        {
            RpcErrors.RpcErrors400.GroupcallInvalid.ThrowRpcError();
            return null!;
        }

        var isParticipant = groupCall.Participants.Any(p =>
            p.PeerType == (int)PeerType.User &&
            p.PeerId == input.UserId &&
            !p.Left);
        if (!isParticipant && groupCall.CreatorId != input.UserId)
        {
            RpcErrors.RpcErrors400.GroupcallInvalid.ThrowRpcError();
            return null!;
        }

        var updates = GroupCallStateHelper.Updates(GroupCallStateHelper.CreateEncryptedMessageUpdate(
            groupCall,
            new TPeerUser { UserId = input.UserId },
            obj.EncryptedMessage));
        await GroupCallStateHelper.PushUpdatesToCallSubscribersAsync(
            objectMessageSender,
            groupCall,
            updates,
            input.UserId);

        return new TBoolTrue();
    }
}
