// <auto-generated />
namespace MyTelegram.Messenger.Handlers.Auth;
/// <summary>
/// Possible errors
/// Code Type Description
/// 400 PHONE_NUMBER_INVALID The phone number is invalid.
/// <para><c>See <a href="https://corefork.telegram.org/method/auth.checkPaidAuth"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✔]
/// </remarks>
internal sealed class CheckPaidAuthHandler(
    IQueryProcessor queryProcessor,
    ICommandBus commandBus,
    IOptionsMonitor<MyTelegramMessengerServerOptions> options)
    : RpcResultObjectHandler<MyTelegram.Schema.Auth.RequestCheckPaidAuth, MyTelegram.Schema.Auth.ISentCode>, IObjectHandler
{
    protected override Task<MyTelegram.Schema.Auth.ISentCode> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Auth.RequestCheckPaidAuth obj)
    {
        // TODO: implement checkPaidAuth later — paid-auth state/purchase handling is in place
        //       (AppCodeState.PaidAuthRequired/PaidAuthFormId/PaidAuthCompleted are populated by the
        //       payment-completion handling). This handler body is intentionally deferred.
        throw new NotImplementedException();
    }
}
